### ISSUE TITLE
Unable to save changes after logging in via Github

### ISSUE THREAD

**Issue by tristanofalls** [Mottokrosh/Sheet#92]
[maxluoXIII](https://github.com/maxluoXIII)'s approach ([Issue #89](https://github.com/Mottokrosh/Sheet/issues/89)) seems to have repaired the ability to login and see your previous characters post-Github-API-change. (Thanks!) But after logging in, I'm unable to make any changes to sheets, archive characters, or anything else that involves saving. It just kicks me back to the login screen when trying to save. It seems very similar to [Issue #64](https://github.com/Mottokrosh/Sheet/issues/64) .

**Comment by maxluoXIII** [comment]
Thanks for bringing this up, I can replicate this issue. It seems to happen with older characters made before the authentication change. I think I know what the issue is and it should be a relatively quick fix, but I won't be able to work on it for a few more hours. 

If you absolutely need to use the sheet in the meantime, creating a new character and porting the info should suffice.
